[folders]
# キーはpathsの後に何か適当につけてください
# 設定例
# paths=C:\Downloads
# paths2=C:\Desktop
paths=C:\Users\shun1\Downloads\新しいフォルダー2\video-app\backend\assets\sample_videos

[settings]
# mp4ではなくHLSで視聴したい場合はコメントアウトを外してください
# 遅延は減少しますが、容量をとります
# hls_mode=true